spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://postgres-company:5432/avb_invest_company_db
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example.companyservice: DEBUG
  file:
    name: logs/company-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%M - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  default-produces-media-type: application/json
