server:
  port: 3333

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/