spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://my-postgres:5432/avb_invest
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  default-produces-media-type: application/json

